### ISSUE TITLE
Tracking: The to-do list

### ISSUE THREAD

**Issue by whhe** [oceanbase/ob-example#16]
The following list shows the latest tasks to add example projects for different tech stacks. 

If what you want is not listed, please reply below. 

#### Java

- [ ] https://github.com/oceanbase/ob-example/issues/10
- [ ] https://github.com/oceanbase/ob-example/issues/11
- [ ] https://github.com/oceanbase/ob-example/issues/12
- [ ] https://github.com/oceanbase/ob-example/issues/14
- [ ] https://github.com/oceanbase/ob-example/issues/15

#### C#

- [ ] https://github.com/oceanbase/ob-example/issues/13

**Comment by whhe** [comment]
Example : https://github.com/oceanbase/ob-samples/pull/35

**Comment by whhe** [comment]
> Can I add a demo of cpp working with OceanBase?

Yeah sure, welcome to contribute.
